### ISSUE TITLE
Bug when computing hash from file using XXHash64 or State64!

### ISSUE THREAD

**Issue by alpakeno** [wilhelmliao/xxHash.NET#3]
I have tried to compute a hash from a file using State32 and the result is the same as the xxhsum.exe.
but when i tried to use State64 the computed hash result is wrong ( tried both XXHash64 and XXHash.State64 ) 

Tried it using VB.NET 2010 on win 8.1 (x64)

**Comment by wilhelmliao** [comment]
Thank you for the feedback. @alpakeno !

**Comment by wilhelmliao** [comment]
Fixed and released at https://github.com/wilhelmliao/xxHash.NET/releases/tag/v1.0.1

**Comment by alpakeno** [comment]
working now as expected, thanks.
