### ISSUE TITLE
InternalUpdateState64() processes wrong data from temp buffer which can result in an exception

### ISSUE THREAD

**Issue by MarcKamradt** [wilhelmliao/xxHash.NET#4]
https://github.com/wilhelmliao/xxHash.NET/blob/3c1fbc91cfa96d0e3139035f6b4897bd6fda7906/src/Extensions.Data.xxHash/XXHash.cs#L813

The InputTextStream helper is initialized with an offset of "state.memsize" but the temp buffer must always be processed from the very beginning to the end.

The exception can be reproduced by updating the state with a single byte first and then updating it again with a bigger file.

Taking a look the code this is probably also true for InternalUpdateState32() but I have not tried to reproduce it with the 32 bit version.

**Comment by wilhelmliao** [comment]
@MarcKamradt, thank you for the report. The issue had been fixed on InternalUpdateState32() and InternalUpdateState64().

**Comment by MarcKamradt** [comment]
Just downloaded v1.0.2 via NuGet and the issue seems fixed.
