### ISSUE TITLE
Switch to .NET Core framework

### ISSUE THREAD

**Issue by MarcKamradt** [wilhelmliao/xxHash.NET#5]
I think the package could easily be switched to .NET Core.

I integrated the source files into a .NET Core 2.0 project for debugging purposes and it worked just fine.

When using the NuGet package there will be a warning that the framework may not be compatible with .NET Core 2.0

**Comment by wilhelmliao** [comment]
No problem! noted on my todo list.

**Comment by wilhelmliao** [comment]
Switched to .NET core: https://www.nuget.org/packages/Extensions.Data.xxHash.core20
